#!/bin/sh

case $1 in
    -c)
        CONFIG_FILE=$2
        shift 2
        ;;
    --pidfile)
        PID_FILE=$2
        shift 2
        ;;
    *)
        echo "Unsupported option: $1"
        exit 1
        ;;
esac

export CONFIG_FILE PID_FILE

while [ true ]; do
  (/usr/bin/darkice -c $CONFIG_FILE && echo $! > $PID_FILE) | logger -t darkice -i
  logger -t darkice-safe -i "darkice has been stopped, restart"
  sleep 5
done
